### ISSUE TITLE
Set up a proper release process

### ISSUE THREAD

**Issue by blackboxlogic** [blackboxlogic/OsmApiClient#8]
The project (and nuget package?) should probably live with OsmSharp, and use their build chain and other tooling.

**Comment by HarelM** [comment]
Unfortunately, I don't: I think this package should depend on OSMSharp rather than include it - and therefore it needs the latest changes merge to OSM Sharp.
I also think the first non pre-release version should come from the OSM Sharp pipe line.
Codewise - I do think this library is ready.
@xivk - I think it's time to fork this library into OSM sharp and create its first non pre-release package.

**Comment by HarelM** [comment]
Yup, I use OSMSharp in my production server, it performs very well, so I needed to fix a few small issues with the OSM API, and you continued my work here.
But unfortunately, I don't have any privileges on the OSMSharp core repository :-(

**Comment by xivk** [comment]
Any action that you are waiting for me to do? I have a little bit of time tomorrow. 

Do I fork this project or copy it to a repository hosted under OsmSharp? If I give you access @HarelM you can just move it over or something?

There is probably some work needed first before a release is possible, like removing OsmSharp as a git submodule and integrating it as a package and probably integrating the latest changes.

**Comment by HarelM** [comment]
To elaborate what @blackboxlogic wrote: in order to remove the submodule that is currently there we need you to merge the following PR:
https://github.com/OsmSharp/core/pull/82 
After that we need you to create an OSM Sharp NuGet package so we can referenced it from this project. And after that, we need to understand how to integrate it in the OSM Sharp company repository, here at github.
If you can do it tomorrow it would be super! :-) Thanks!

**Comment by xivk** [comment]
Done now, ping me when you are ready with this one.

**Comment by HarelM** [comment]
@xivk does merging to develop branch will create a NuGet package automatically?

**Comment by xivk** [comment]
Yes, it is building now...

**Comment by blackboxlogic** [comment]
@HarelM do you think it would be ok to reference a [pre-rease](https://www.nuget.org/packages/OsmSharp/7.0.0-pre001)

**Comment by HarelM** [comment]
As a rule, a pre-release nuget can reference a pre release and a stable should only reference stable nugets. So until the stable version is released we should publish a pre-release, I think...

**Comment by blackboxlogic** [comment]
What's the next step here?

**Comment by HarelM** [comment]
Moving this project to OSMSharp i guess...
I still want to try and integrate it in my web site but this can be done in parallel...

**Comment by blackboxlogic** [comment]
@xivk We're hoping for your guidance for moving this into OSMSharp's domain.

**Comment by blackboxlogic** [comment]
Seems like this stalled?

**Comment by xivk** [comment]
I added this project:

https://github.com/OsmSharp/osm-api-client

And I've given you access to it, feel free to push the code there and then we can setup a build process.

**Comment by xivk** [comment]
Sorry things are move so slowly, once this is setup you will have all the freedom to manage this. 

@blackboxlogic can you email me so I can make a useraccount on the build server?

**Comment by blackboxlogic** [comment]
@xivk Your email isn't listed in github (or I just can't find it)

I can be reached at blackboxlogic@gmail.com

**Comment by xivk** [comment]
You should now have access to the build server too, just sent you over some details.

**Comment by blackboxlogic** [comment]
> I added this project:
> https://github.com/OsmSharp/osm-api-client
> And I've given you access to it, feel free to push the code there and then we
I don't seem to have write access to that project in github.
> remote: Permission to OsmSharp/osm-api-client.git denied to blackboxlogic.
> fatal: unable to access 'https://github.com/OsmSharp/osm-api-client.git/': The requested URL returned error: 403

Also, looking to retain commit history, would it make sense to (in order of preference):
* [Tansfer](https://help.github.com/en/articles/transferring-a-repository)
* [Copy](https://help.github.com/en/articles/duplicating-a-repository)
* Fork from this project
* Just commit the files as they are now, losing history

Thoughts?

**Comment by xivk** [comment]
If you just clone this repo and then do:

`git remote add origin git@github.com:OsmSharp/osm-api-client.git`
`git push -u origin master`

You still need to accept the invite I sent you before you have push access.

**Comment by blackboxlogic** [comment]
I don't have permissions in TeamCity to create a new project.

**Comment by blackboxlogic** [comment]
@xivk Just checking in.

**Comment by blackboxlogic** [comment]
@HarelM I've got github actions set up.
Commits to master trigger a build. If the project's "Package Version" has been updated then a nuget package gets published with that version.
I just released 0.0.1-beta.7 which treats versions and Ids as longs (instead of int). I'm waiting for OsmSharp to release version 7 before I put this to version 1.0.0
I'm open to feedback and improvement.

@xivk can you delete https://github.com/OsmSharp/osm-api-client and https://build.itinero.tech/viewType.html?buildTypeId=OsmSharp_OsmApiClient I appreciate the time you've given me along the way. Thank you.

**Comment by HarelM** [comment]
I'm using this code in production and I didn't encounter any issue with it. Thanks!
I don't have anything currently to add to this client.
The only comment I have currently is how the functional test are written - It might be better to use the MSTest and split every operation to its own test by using `[TestInitialize]` and `[TestCleanup]` so that you can test every part of the API separately.
Other than this minor comment I think this is a great repo, kudos!
